### ISSUE TITLE
TechGirlz-CRACK_IT

### ISSUE THREAD

**Issue by srishti-coder** [MozPhoenixClubJUET/JUEThacks2020#14]
**Before you start, please follow this format for your issue title**:  

## ℹ️ Project information
_Please complete all applicable._

- **Project Name**:CRACK_IT
- **Short Project Description**: A website created for students which can provide them all information to crack JEE and be an IITian.
- **Team Name**: TechGirlz
- **Team Members**: Srishti Mishra(@srishti-coder),Sonali Pandey(@Sonali1772),Mansi Tiwari(@mansi2702),Harshita Tripathi(@ht1892),Tanya Singh(@tanyasingh-23)
- **Demo Link**: https://drive.google.com/file/d/1FK1CEofVAlL4gnt-NLaLYSmzwiOTH2_f/view?usp=drivesdk
- **PULL REQUEST Link**:#13
- **Labels**: Open Innovation No Track Followed

## 🔥 Your Pitch
CRACK_IT is a project made by TechGirlz which helps JEE aspirants.Student can not only check the best books for JEE but can also download it for free and those who want to purchase them can purchase it also.Further,it provides you list of top notch coaching centers with their address and contact information.Its is different form others in aspect of amazing UI as well as the information provided which is up to the mark.

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
