### ISSUE TITLE
Daunt Less-CoVid Trakker

### ISSUE THREAD

**Issue by jainaagam96** [MozPhoenixClubJUET/JUEThacks2020#17]
**Before you start, please follow this format for your issue title**:  
Daunt Less - CoVid Trakker

## ℹ️ Project information
_Please complete all applicable._

- **Project Name**: CoVid Trakker
- **Short Project Description**: Covid-19 data transparency an consulting app
- **Team Name**: Daunt Less
- **Team Members**: Aagam jain(@jainaagam96), Aman Ghatiya(@aman5683), Shantanu Pandey(@shan6116),  Aakansha singh(@aakansha9425),  Akshat Upadhyay(@AkshatUpadhyay)
- **Demo Link**: https://drive.google.com/file/d/1YgNINN990LXa-ds2WEFniSj7hOqOh-aD/view?usp=drivesdk
- **PULL REQUEST Link**: #16 
- **Labels**: covid, covid software track

## 🔥 Your Pitch
Our team DauntLess believe’s that the best way to build  a successful project is by giving it’s users the most possible transparency regarding the data, stats and accuracy.
Hence we try to make a covid tracking software which we named as “CoVid Trakker” , so as to provide the user with an interface in their hand giving them the required and essential data regarding the Covid-19 situation and relatable stuffs.

We made an app which authenticate the user with their respective mobile numbers which sends a OTP verification on the provided number by the user.
As the user is given access to the application the user can get the exact data provided by the government regarding the total death cases active patients and cases total recovered cases and the confirmed cases.
Not just total but the app provides the user ,the stats about the state data of the recovery death and confirmed cases of covid-19.
To make it more transparent for users we even provided the district confirmed data so as the user can be more strict regarding the situation about his locality or region.

We designed the logo and app icon of the app so as to give it a more professional and good look.

So what’s new in our app…
We provide a proper hospitality details regarding the issue if faced by people by just asking for location of user and provide them the best and nearby medical facility available .

We even provide the Do’s and dont’s of COVID as provided by WHO and basic details about the Dailys meals so as to remain fit and far away from misconception and false information.

A feature similar to chatbot is also added so as user can self test on various categories, if they need a doctor seriously or even a short home quarantine can be enough for them.

As per government shortage of beds scheme a 3 days 7 days and 14 days quarantine is categorised so as to give user a good and important information regarding their health.

Through maps and hospitals details the user can even ask for doctor whom they don’t even met once for consult and take a look for their health checkups.

We used technologies like Android Studio,Adobe XD, Adobe Photoshop, Photopea , Postman, firebase to accomplish this task. 

We even thought some of the possible future updates that we can add into them one among them is providing the details that the person who is walking can be notify whether the region or locality he is moving is either red green or orange zone depending upon the data and details.

Lastly, its been a great project to work on and our team is thankful to JuetHacks and Mozilla Phoenix Club for such Opportunity.
Thank You.

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
