### ISSUE TITLE
CODE CRAFTERS - CRAFTER'S MASK DETECTOR 

### ISSUE THREAD

**Issue by ishaandwivedi1234** [MozPhoenixClubJUET/JUEThacks2020#18]
## ℹ️ Project information

- **Project Name**: Crafter's Mask Detector
- **Short Project Description**: A Web Based Computer Vision Module To Monitor Mask On People's Face
- **Team Name**: Code Crafters
- **Team Members**: Ishaan Dwivedi(@ishaandwivedi1234), Abhishek Sharma (@Abhishek-Sharma), Harsh Modi (@Harshmodi559) , Abhishek Gupta (@abhishek-0-8) ,Jiggesh Raghuvanshi (@jiggesh11)
- **Demo Link**: _https://drive.google.com/file/d/1m9fES5NAz_8CcyUFnJvj48bSACUmSsR2/view?usp=sharing_
- **PULL REQUEST Link**: _#15_
- **Labels**: _COVID, COVID software track_

## 🔥 Your Pitch
* What  is Crafter's Mask Detector ?

The Crafter's Mask Detector is a ML based web module, which detects whether a person is wearing a mask or not   

* Why Crafter's Mask Detector ?

Although there are several mask detection modules available on internet as software , But they don't provide easy access to a non-tech guy. Whereas our mask detection system is server based , which makes it possible for common man (non-tech guys) to use it without installing a bit in their system.  Also none of the face mask detection system uses VOICE ASSISTANT to monitor the crowd.

* How to use it?

The simplest way to use it is , to connect an IP Camera / Webcam / CCTV to the module and ask your crowd to enter if the module allows them , as our module has an integrated voice assistant. 

* Who can use it ?

However the target audience for this module is the small scale shopkeepers , micro marts , government offices , public places / gathering , university, schools etc. But any constructive use is always welcomed !! 

* How it works ?

The Crafter's Mask Detector Module is trained through 1500 image data sets , using two classes 
1. With Mask
2. Without Mask
* The trained ML Model is then used by Open Source Computer Vision to feed the faces 
    to the ML Model ,which then returns the probability of mask or no mask
* On the basis of probability the bounding box is displayed around face , with two colors 
    1. Red ( With No Mask Label)
    2. Green (With Mask Label)
* Simultaneously the voice assistant code is invoked which tells the result to the person in-front.  

## 🔦 Any other specific thing you want to highlight?
_1 . It's way more than just a mask detector , rather it's a module with various features ._
_2 . It has voice assistant integration , which makes it easy for visually impaired & less literate people    ._
_3 . It can even be connect to an IP camera , which makes it distance controlled system._
_4 . It's FREE & EASY to use ._

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
