### ISSUE TITLE
No_Goals - Covid Dashboard

### ISSUE THREAD

**Issue by priyasingh456** [MozPhoenixClubJUET/JUEThacks2020#20]
**Before you start, please follow this format for your issue title**:  
TEAM NAME - PROJECT NAME

## ℹ️ Project information
_Please complete all applicable._

- **Covid Dashboard**:
- **A Dashboard to help users to complete their some of the essential tasks during pandemic**: _One line crisp description of your project_
- **No_Goals**: 
- **Priya Parihar - @priyasingh456      Gaurav Kumar - @lucifer0987   Sakshi Sahu - @sakshisahu234     Eshita - @Eshitapooni   Abhishek Pal - @abhipal1244
**: _Mention their Names & tag their GitHub handles(use @ to tag them here)_
- **shorturl.at/egs78**: _(if any, this might contain a website/ mobile application link/ short video, etc.)_
- **https://github.com/MozPhoenixClubJUET/JUEThacks2020/pull/22**: _Provide us the link to the pull request you created_
- **COVID Software**: _Mention the labels you wish to apply here_

## 🔥 Your Pitch
_Kindly write a [pitch](https://medium.com/next-media-accelerator/pitch-your-hackathon-product-in-3-minutes-and-conquer-the-jury-9f86bfbdba6f) for your project. Please do not use more than 500 words_
During this pandemic, everyone is taking precautions and false information is everywhere. This android application fetches data from trusted APIs and displays them to the users so that they can remain informed and take precautions.

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
