### ISSUE TITLE
IGNORAMUS-IGNORAMUSINDIA

### ISSUE THREAD

**Issue by Anirudh-Chauhan** [MozPhoenixClubJUET/JUEThacks2020#24]
**Before you start, please follow this format for your issue title**:  
IGNORAMUS-IGNORAMUSINDIA

## ℹ️ Project information
_Please complete all applicable._

- **Project Name**: IGNORAMUSINDIA
- **Short Project Description** :  A website from which the people or laborers stuck at their homes or are away from their working place and lost their jobs because of this pandemic. 
- **Team Name**:  IGNORAMUS
- **Team Members**: Anirudh Singh Chauhan - (@Anirudh-Chauhan), Devik Sanghvi (@deviksanghvi), Ashish Singh (@Ashish-singh19), Hari Patidar(@hari-patidar), Mitesh Kumar(@mitesh-kumar)
- **Demo Link**: https://drive.google.com/file/d/1kipU7JUwfw1I1pMAV4z0O9Z5w9KIwaxC/view?usp=sharing
- **PULL REQUEST Link**: https://github.com/MozPhoenixClubJUET/JUEThacks2020/pull/23 (#23 )
- **Labels**: Open Innovation, No Track Followed

## 🔥 Your Pitch
We built a website from which the people or laborers stuck at their homes or are away from their working place and lost their jobs because of this pandemic. The website will allow people to do a remote work of their choice be that online teaching or any other work and students can take additional benefits from this in learning new things.
The project is fully based on Atamnirbhar Bharat. For achieving this we need to create a platform common for vendors, service providers, and consumers through which there is transparency in the trade with minimal or no third-party intervention.

## 🔦 Any other specific thing you want to highlight?
PPT for the project : https://docs.google.com/presentation/d/1On3qDwo_x82WuzVKEVZgCOrJiRGcbxCIN4j3FxXjb88/edit?usp=sharing

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
