### ISSUE TITLE
Tech-Fit - HealthCare

### ISSUE THREAD

**Issue by riya028** [MozPhoenixClubJUET/JUEThacks2020#25]
**Before you start, please follow this format for your issue title**:  
Tech-fit - HealthCare

## ℹ️ Project information
_Please complete all applicable._

- **HealthAndCure**:
- **This is the website for HealthCare that helps people to take prevention against COVID-19**: _One line crisp description of your project_
- **Tech-Fit**: 
- **Riya Gupta @riya028 , Rangoli @Rangoli05 , Sejal Jain @Sejaljain705 , nishita @nishitachaturvedi4 ,  ritika @ritikasri1799**: _Mention their Names & tag their GitHub handles(use @ to tag them here)_
- **https://riya028.github.io/**: _(if any, this might contain a website/ mobile application link/ short video, etc.)_
- **https://github.com/MozPhoenixClubJUET/JUEThacks2020/pull/21**: _Provide us the link to the pull request you created_
- **open innovation no track **: _Mention the labels you wish to apply here_

## 🔥 Your Pitch
We have made a website which awares the user about COVID-19. This website tells the user on how to prevent oneself from corona virus.

## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
