### ISSUE TITLE
BUG BUSTERS - NEEROG JEEVAN

### ISSUE THREAD

**Issue by DARK-art108** [MozPhoenixClubJUET/JUEThacks2020#9]
## ℹ️ Project information

- **Project Name**: Neerog Jeevan
- **Short Project Description**: _A simple web application that predicts the chances for a person's being infected by COVID-19 based on symptoms._
- **Team Name**:  Bug Busters
- **Team Members**: _Ritesh Yadav (@DARK-art108), Param Siddharth (@paramsiddharth), Paridhi Malav (@paridhi1314), Harsh Marolia (@HarshMarolia), and Sushant Sharma (@shinchi312)_
- **Demo Link**: _[Neerog Jeewan](http://covid-predict-app.herokuapp.com/)_
- **PULL REQUEST Link**: #12 
- **Labels**: _COVID, COVID software track_

## 🔥Pitch
A simple web application that predicts the chances for a person's being infected by COVID-19 based on symptoms. 

 A dummy dataset and machine learning model are being used for the prediction. This application has been built in HTML, CSS, JavaScript, and Python (Flask, NumPy, Pickle, Scikit-Learn). 

Idea:

• COVID-19 Dashboards were becoming very common. We wanted to do something new; Something never has done before.
 • We wanted to build an application that integrates machine learning with a web interface. It would be a learning experience.
 • The application can easily be integrated with hospital patient databases to help in contactless recognition of Coronavirus suspects. 
 • As COVID-19 grows asymptomatic, there won't be a need to keep a track of the technology needed for prediction. The log database can easily be used to build another database, ready for use with the evolved virus. 

What one can achieve from the application:

• A good place to go if you wish to make sure that your symptoms don't point towards a COVID-19 infection.
• By having a look at recent queries, one can get an idea of the performance of the virus in surroundings.
• A glimpse of headlines on the homepage.
• A user-friendly environment, where the user doesn't have to be concerned about the intimidating stuff going on in the background.
• A time-ready model trained perfectly for predicting COVID-19 infection probability while only making itself better with each prediction.

Hosting the application:

• A web server would be required to host it online.
 • A static IP, preferably with a domain/subdomain name attached, would be good for serving the application to users.
 • The server must support Python for hosting a Flask web application.
 • An SSL Certificate would be good for increasing security and customer trust. 
 • Other details on deployment are available in the README file.
• The UI is easily customizable because the layout and templates are preformatted with Jinja. The service would only require to make the relevant changes in the layout file.

## 🔦 Any other specific thing you want to highlight?
- The application is unique — While building it, we took into account that no other similar application existed.
- We used the best possible solutions for each of the applications. It is customizable and can easily work with any dataset of proper format.
- It is our first ever project of machine learning integration with a web interface! It was a fascinating experience.

## ✅ Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have mentioned the correct labels.
- [x] You have provided all the information correctly.

**Comment by srivastavaayu** [comment]
Thank you for participating in JUETHacks 2020! We hope you had a great time and got to learn something! See you next year! Peace!
